/* tslint:disable */
/* eslint-disable */
/**
 * Tutor
 * Event Manager Backend service is based on Strapi v3 JS framework.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aram@dasmeta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EventsubscriptionsRecordfailureBody
 */
export interface EventsubscriptionsRecordfailureBody {
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionsRecordfailureBody
     */
    topic?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionsRecordfailureBody
     */
    subscription?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionsRecordfailureBody
     */
    eventId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionsRecordfailureBody
     */
    traceId?: string;
    /**
     * 
     * @type {any}
     * @memberof EventsubscriptionsRecordfailureBody
     */
    error?: any;
}
