/* tslint:disable */
/* eslint-disable */
/**
 * Tutor
 * Event Manager Backend service is based on Strapi v3 JS framework.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aram@dasmeta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EventsubscriptionEventId
 */
export interface EventsubscriptionEventId {
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionEventId
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionEventId
     */
    traceId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionEventId
     */
    topic?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionEventId
     */
    dataSource?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionEventId
     */
    entity?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionEventId
     */
    entityId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionEventId
     */
    messageId?: string;
    /**
     * 
     * @type {any}
     * @memberof EventsubscriptionEventId
     */
    data?: any;
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionEventId
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionEventId
     */
    updatedBy?: string;
}
