/* tslint:disable */
/* eslint-disable */
/**
 * Tutor
 * Event Manager Backend service is based on Strapi v3 JS framework.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aram@dasmeta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventsubscriptionEventId } from './eventsubscription-event-id';
/**
 * 
 * @export
 * @interface EventSubscription
 */
export interface EventSubscription {
    /**
     * 
     * @type {string}
     * @memberof EventSubscription
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EventSubscription
     */
    topic?: string;
    /**
     * 
     * @type {string}
     * @memberof EventSubscription
     */
    subscription?: string;
    /**
     * 
     * @type {EventsubscriptionEventId}
     * @memberof EventSubscription
     */
    eventId?: EventsubscriptionEventId;
    /**
     * 
     * @type {boolean}
     * @memberof EventSubscription
     */
    isError?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EventSubscription
     */
    isPreconditionFail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EventSubscription
     */
    isSuccess?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EventSubscription
     */
    traceId?: string;
    /**
     * 
     * @type {any}
     * @memberof EventSubscription
     */
    error?: any;
}
