/* tslint:disable */
/* eslint-disable */
/**
 * Tutor
 * Event Manager Backend service is based on Strapi v3 JS framework.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aram@dasmeta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EventsRepublishsingleerrorBody
 */
export interface EventsRepublishsingleerrorBody {
    /**
     * 
     * @type {string}
     * @memberof EventsRepublishsingleerrorBody
     */
    topic?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsRepublishsingleerrorBody
     */
    subscription?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EventsRepublishsingleerrorBody
     */
    events?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EventsRepublishsingleerrorBody
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof EventsRepublishsingleerrorBody
     */
    limit?: number;
}
