/* tslint:disable */
/* eslint-disable */
/**
 * Tutor
 * Event Manager Backend service is based on Strapi v3 JS framework.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aram@dasmeta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EventsubscriptionsRecordstartBody
 */
export interface EventsubscriptionsRecordstartBody {
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionsRecordstartBody
     */
    topic?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionsRecordstartBody
     */
    subscription?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionsRecordstartBody
     */
    eventId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsubscriptionsRecordstartBody
     */
    traceId?: string;
}
