/* tslint:disable */
/* eslint-disable */
/**
 * Tutor
 * Event Manager Backend service is based on Strapi v3 JS framework.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aram@dasmeta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NewEventStats
 */
export interface NewEventStats {
    /**
     * 
     * @type {string}
     * @memberof NewEventStats
     */
    subscription?: string;
    /**
     * 
     * @type {string}
     * @memberof NewEventStats
     */
    topic?: string;
    /**
     * 
     * @type {number}
     * @memberof NewEventStats
     */
    error?: number;
    /**
     * 
     * @type {number}
     * @memberof NewEventStats
     */
    fail?: number;
    /**
     * 
     * @type {number}
     * @memberof NewEventStats
     */
    missing?: number;
    /**
     * 
     * @type {number}
     * @memberof NewEventStats
     */
    preconditionFail?: number;
    /**
     * 
     * @type {number}
     * @memberof NewEventStats
     */
    subscriptionCount?: number;
    /**
     * 
     * @type {number}
     * @memberof NewEventStats
     */
    success?: number;
    /**
     * 
     * @type {number}
     * @memberof NewEventStats
     */
    topicCount?: number;
    /**
     * 
     * @type {number}
     * @memberof NewEventStats
     */
    total?: number;
    /**
     * 
     * @type {string}
     * @memberof NewEventStats
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof NewEventStats
     */
    updatedBy?: string;
}
